### ISSUE TITLE
rest-service.guides.spring.io not running

### ISSUE THREAD

**Issue by jvalkeal** [spring-guides/gs-consuming-rest-angularjs#2]
Readme is a little unclear if I need to have similar service `rest-service.guides.spring.io` running on a localhost.

Currently this will give 404:
```
$ curl http://rest-service.guides.spring.io/greeting
404 Not Found: Requested route ('rest-service.guides.spring.io') does not exist.
```

**Comment by gregturn** [comment]
I think the service on PWS that we stood up may be down. We need better monitoring on it.

**Comment by dsyer** [comment]
Fixed now.
