### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by vadimzham** [spring-guides/gs-consuming-rest-angularjs#3]
Hi. I followed your manual and i got this error: i googled it and i saw that are much people gettin this. How you wrote the guide, man? Here are no any information about allowing CORS.

XMLHttpRequest cannot load http://rest-service.guides.spring.io/greeting. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

**Comment by dsyer** [comment]
I think this guide changed at some point (4a6c5bb78c) to point to an external service. That external service probably used to have a CORS filter, but no longer does. I don't know where the code is for that or who deployed it (@gregturn might know).

**Comment by pcssi** [comment]
:+1:

**Comment by dsyer** [comment]
Should be working now. I'll update this guide README so there is a clue where the code came from for the deployed service.
