### ISSUE TITLE
hello.js ,function Hello as controller does not work

### ISSUE THREAD

**Issue by phxism** [spring-guides/gs-consuming-rest-angularjs#6]
1.
```
<html ng-app="demo">
```
2.
```
angular.module('demo', [])
.controller('Hello', function($scope, $http) {
    $http.get('http://rest-service.guides.spring.io/greeting').
        success(function(data) {
            $scope.greeting = data;
        });
});
```

**Comment by dsyer** [comment]
Where's your `ng-controller`?

**Comment by phxism** [comment]
I mean that hello.js
`function Hello($scope, $http) {
    $http.get('http://rest-service.guides.spring.io/greeting').
        success(function(data) {
            $scope.greeting = data;
        });
}`
does not work and gets an error,when  should change to 
`angular.module('demo', [])
.controller('Hello', function($scope, $http) {
    $http.get('http://rest-service.guides.spring.io/greeting').
        success(function(data) {
            $scope.greeting = data;
        });
});`
and in index.html add ng-app="demo"

**Comment by dsyer** [comment]
I know, but you haven't shown your whole index.html. It has to have an element with `ng-controller="Hello"` for your change to do anything useful.

**Comment by phxism** [comment]
sorry for delaying.
### the index.html

<!doctype html>
<html ng-app="demo">
<head>
<title>Hello AngularJS</title>
<script src="
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js
"></script>
    <script src="hello.js"></script>
</head>

<body>
<div ng-controller="Hello">
<p>The ID is {{greeting.id}}</p>
<p>The content is {{greeting.content}}</p>
</div>
</body>
</html>

### the hello.js

angular.module('demo', [])
.controller('Hello', function($scope, $http) {
    $http.get('http://rest-service.guides.spring.io/greeting').
        success(function(data) {
            $scope.greeting = data;
        });
});


2016-09-04 1:43 GMT+08:00 Dave Syer <notifications@github.com>:

**Comment by dsyer** [comment]
Works for me. What happens when you load the app in a browser?

**Comment by phxism** [comment]
if hello.js like that 
`function Hello($scope, $http) {
    $http.get('http://rest-service.guides.spring.io/greeting').
        success(function(data) {
            $scope.greeting = data;
        });
}`
then loading  the app in a browser gets error
`angular.js:12330Error: [ng:areq] http://errors.angularjs.org/1.4.3/ng/areq?p0=Hello&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:6:416
    at Sb (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:22:18)
    at Qa (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:22:105)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:79:497
    at x (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:59:501)
    at S (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:60:341)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:54:384)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:54:407)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js:54:407)(anonymous function) @ angular.js:12330`

**Comment by dsyer** [comment]
I finally understood your issue (please try to be more explicit if you submit any more). Something changed in AngularJS since this guide was published (anonymous apps with controllers as functions apparently used to be a thing and they are no longer). We updated the Angular version but didn't check that it works, I think.

Should be fixed now.
